/**
 * Persistence boundary for the `adaptations` table.
 *
 * The row type (`AdaptationRow`) is defined HERE from our canonical types, NOT
 * from the generated `src/integrations/supabase/types.ts` — that file still
 * reflects the OLD `adaptations` shape and is only regenerated by `make
 * gen-types` AFTER the M6 migration runs. Until then, every `.from("adaptations")`
 * call carries ONE localized cast (`as never`) so the new columns typecheck.
 *
 * The `adaptation_result` blob is validated with `safeParseDocument` /
 * `AdaptationResultSchema` before every write and after every read, so a
 * malformed blob never silently round-trips.
 */

import { supabase } from "@/integrations/supabase/client";
import {
  AdaptationResultSchema,
  type AdaptationResult,
} from "@/lib/adaptation/canonical/schema";

// ---------------------------------------------------------------------------
// Types — defined here, decoupled from the generated types.ts
// ---------------------------------------------------------------------------

export type AdaptationStatus = "draft" | "ready";

export type AdaptationRow = {
  id: string;
  user_id: string;
  barrier_profile_id: string | null;
  title: string;
  original_activity: string;
  activity_type: string | null;
  barriers_used: unknown;
  adaptation_result: AdaptationResult;
  status: AdaptationStatus;
  credits_spent: number;
  created_at: string;
  updated_at: string;
};

/** A list item omits the heavy result blob to keep the history list lean. */
export type AdaptationListItem = Omit<AdaptationRow, "adaptation_result">;

/** The data needed to create/update an adaptation. */
export type AdaptationPayload = {
  user_id: string;
  title: string;
  original_activity: string;
  activity_type: string | null;
  barrier_profile_id: string | null;
  barriers_used: unknown;
  adaptation_result: AdaptationResult;
};

export type UpdateResult =
  | { ok: true; row: AdaptationRow }
  | { ok: false; conflict: true };

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// ONE localized cast: the generated types.ts predates the M6 migration, so the
// supabase client does not know the canonical columns yet. `make gen-types`
// regenerates types.ts after the migration runs, after which this can drop.
function table() {
  return supabase.from("adaptations" as never);
}

/** Validate the result blob before writing; throws on malformed input. */
function assertValidResult(result: AdaptationResult): AdaptationResult {
  return AdaptationResultSchema.parse(result);
}

/** Validate the result blob coming back from the DB; throws on malformed data. */
function parseRow(raw: Record<string, unknown>): AdaptationRow {
  const adaptation_result = AdaptationResultSchema.parse(raw.adaptation_result);
  return { ...(raw as unknown as AdaptationRow), adaptation_result };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Insert a new draft row and return it. */
export async function saveDraft(payload: AdaptationPayload): Promise<AdaptationRow> {
  const adaptation_result = assertValidResult(payload.adaptation_result);
  const { data, error } = await table()
    .insert({ ...payload, adaptation_result, status: "draft" } as never)
    .select("*")
    .single();
  if (error) throw error;
  return parseRow(data as Record<string, unknown>);
}

/**
 * Update an existing adaptation with optimistic concurrency: the update only
 * matches when `updated_at` still equals `expectedUpdatedAt`. If another writer
 * advanced the row first, 0 rows match → return a conflict result.
 */
export async function updateAdaptation(
  id: string,
  payload: Partial<AdaptationPayload>,
  expectedUpdatedAt: string,
): Promise<UpdateResult> {
  const patch: Record<string, unknown> = { ...payload };
  if (payload.adaptation_result !== undefined) {
    patch.adaptation_result = assertValidResult(payload.adaptation_result);
  }
  const { data, error } = await table()
    .update(patch as never)
    .eq("id", id)
    .eq("updated_at", expectedUpdatedAt)
    .select("*")
    .maybeSingle();
  if (error) throw error;
  if (!data) return { ok: false, conflict: true };
  return { ok: true, row: parseRow(data as Record<string, unknown>) };
}

/** Flip an adaptation to the 'ready' status. */
export async function markReady(id: string): Promise<AdaptationRow> {
  const { data, error } = await table()
    .update({ status: "ready" } as never)
    .eq("id", id)
    .select("*")
    .single();
  if (error) throw error;
  return parseRow(data as Record<string, unknown>);
}

/** List the current user's adaptations, newest-updated first (no result blob). */
export async function listAdaptations(): Promise<AdaptationListItem[]> {
  const { data, error } = await table()
    .select(
      "id,user_id,barrier_profile_id,title,original_activity,activity_type,barriers_used,status,credits_spent,created_at,updated_at",
    )
    .order("updated_at", { ascending: false });
  if (error) throw error;
  return (data ?? []) as unknown as AdaptationListItem[];
}

/** Fetch a single adaptation by id, validating the result blob. */
export async function getAdaptation(id: string): Promise<AdaptationRow> {
  const { data, error } = await table().select("*").eq("id", id).single();
  if (error) throw error;
  return parseRow(data as Record<string, unknown>);
}

/** Delete an adaptation by id. */
export async function deleteAdaptation(id: string): Promise<void> {
  const { error } = await table().delete().eq("id", id);
  if (error) throw error;
}
